# Generated by Django 4.2.3 on 2023-07-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_timeentry_delete_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='am_pm',
            new_name='ampm',
        ),
    ]
